version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/spark-publish"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    reviewers:
      - "bajtos"
      - "juliangruber"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "ci"
    reviewers:
      - "bajtos"
      - "juliangruber"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/spark-publish"
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Berlin"

