app = "spark-publish"
primary_region = "cdg"

[env]
  SENTRY_ENVIRONMENT="production"
  MAX_MEASUREMENTS_PER_ROUND="100000"
  SERVICE="publish"

[deploy]
  strategy = "rolling"

[[restart]]
  policy = "always"
