app = "spark-publish"
primary_region = "cdg"

[env]
  SENTRY_ENVIRONMENT="production"
  MAX_MEASUREMENTS_PER_ROUND="150000"
  NPM_CONFIG_WORKSPACE="publish"

[deploy]
  strategy = "rolling"

[[restart]]
  policy = "always"
